name: vic_chat
description: Vic Chat App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.0

  # Agora (video/voice call)
  agora_rtc_engine: ^6.3.2

  # Permissions (mic, camera)
  permission_handler: ^11.3.1

  # Utils
  uuid: ^4.5.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
