- name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/vic-chat.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vic-chat
          path: build/app/outputs/flutter-apk/vic-chat.apk
          retention-days: 7
